In [1]:
import numpy as np


In [4]:
U = np.array([[3,0], [2,2], [4,4], [0,4]])
I = np.array([[1,3],[0,4],[4,3],[1,2],[4,0]])

R_hat = U @ I.T

print(R_hat)

[[ 3  0 12  3 12]
 [ 8  8 14  6  8]
 [16 16 28 12 16]
 [12 16 12  8  0]]
